### ISSUE TITLE
spu: command should not be used for external sites

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-website#106]
It does not make sense to use the spu: command to include content from external sites whose content may vary indepedently:

https://github.com/apache/infrastructure-website/blob/5ae2fe3289ed0888901fb4e2888c4a8edc518b64/content/pages/roadmap.md?plain=1#L5

https://github.com/apache/infrastructure-website/blob/5ae2fe3289ed0888901fb4e2888c4a8edc518b64/content/pages/machines.md?plain=1#L17

**Comment by gstein** [comment]
Background: the roadmap was effectively bogus, and the machines page is not relevant to the public. We're going to keep it on infra-reports.a.o behind and authn wall.
