### ISSUE TITLE
SSH public key is not uploaded to home.apache.org

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-website#107]
This is outdated:

https://github.com/apache/infrastructure-website/blob/bc80d2985b1c00cf40ef5ab9d98035cce0a464da/content/pages/user-ssh.md?plain=1#L55

**Comment by Humbedooh** [comment]
I suppose that's all in LDAPP now. I will let andrew know.

**Comment by cottage14** [comment]
Removed the outdated section
