### ISSUE TITLE
Emergency contact instructions don't make sense

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-website#126]
The section https://infra.apache.org/infra-contact.html#emergency says it is about contacting staff in an emergency, but I could not find how to do so from following the description.

The first 'here' link points to a list of Infra names, but no contact details.
The second 'here' link points to the private committee information file, which AFAICT does not have details of all the Infra team.

**Comment by cottage14** [comment]
- added the full address for littleblackbook.txt
- removed the paragraph related to contacting an Infra team member by SMS.

**Comment by cottage14** [comment]
I think the change is sufficient and appropriate, without adding horizontal lines.

**Comment by cottage14** [comment]
- After consultation with the team, I have removed the paragraph that provided information for contacting team members via SMS
- I have added the full URL for littleblackbook.txt

**Comment by cottage14** [comment]
Yes, it has been deleted as none of its information was relevant any more.
I will be removing the reference to it today.

**Comment by cottage14** [comment]
instructions improved

**Comment by cottage14** [comment]
Added a link to infra.a.o/contact.html at the top of the page

**Comment by cottage14** [comment]
added appropriate link
