### ISSUE TITLE
Cannot re-open issues ...

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-website#127]
https://infra.apache.org/infra-contact.html#reopen implies that issues can be re-opened, and says that this is a common workflow.

However AFAIK INFRA issues cannot be re-opened.

**Comment by itsdheerajdp** [comment]
Actually What's the exact changes you want to have done?

**Comment by itsdheerajdp** [comment]
Fixes #128 
please check the fixes and update me

**Comment by cottage14** [comment]
I have updated the page to explain about opening a new issue, rather than reopening an existing one.
