### ISSUE TITLE
[build-supported-services Page]:The Git/Github link which should redirect to buildbot github repository is redirecting to a invalid link

### ISSUE THREAD

**Issue by itsdheerajdp** [apache/infrastructure-website#155]
**Current Behavior**
The git/github link which is expected to redirect to the github repository of the buildbot is invalid as shown

[buildbot_link_issue.webm](https://github.com/apache/infrastructure-website/assets/107138786/740ef499-a102-4ae6-9dd5-652416c71f48)

**Comment by cottage14** [comment]
This link seems to be working
