### ISSUE TITLE
https://infra.apache.org/asf-yaml - anchor markers ¶ don't appear

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-website#161]
On most other pages, there are pop-up paragraph markers (¶) to make it easy to link to anchors. These don't seem to be present on the asf.yaml page.

**Comment by cottage14** [comment]
This, it turns out, is a transient page. It will be gone by the end of February 6, 2024 and the links to it will point to the README file in a new repo for .asf.yaml. Therefore, I will not make this improvement to this page.
