### ISSUE TITLE
Pelican Markdown metadata must not contain blank lines

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-website#196]
Parsing of the metadata generally stops when a blank line is detected. This can results in metadata appearing as part of the generated page:

For example:
https://github.com/apache/infrastructure-website/blob/c96d7927255e7069ce51bf530b7a59096127a299/content/pages/release-publishing.md?plain=1#L3

appears as:

https://github.com/apache/infrastructure-website/blob/4d7fa8ef8740321d4f4edfa16a59a6fc03144507/output/release-publishing.html#L75

There are lots of other such examples

**Comment by cottage14** [comment]
Thank you for the info. I have expunged blank lines in the metadata

**Comment by cottage14** [comment]
Thank you for the info. I have expunged blank lines in the metadata
