### ISSUE TITLE
Misleading information on contact page

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-website#39]
The contact page [1] says:

"General inquiries and questions should go to one of our user mailing lists:"

It then lists users@, commits@ and issues@

However it does not make sense to send enquiries to commits@ or issues@
The page should probably mention that users@ and commits@ are private lists -- only issues@ is public
It would also be useful to provide archive links

[1] https://infra.apache.org/contact.html

**Comment by zokaw** [comment]
> The contact page [1] says:
> 
> "General inquiries and questions should go to one of our user mailing lists:"
> 
> It then lists users@, commits@ and issues@
> 
> However it does not make sense to send enquiries to commits@ or issues@
> The page should probably mention that users@ and commits@ are private lists -- only issues@ is public
> It would also be useful to provide archive links
> 
> [1] https://infra.apache.org/contact.html

**Comment by dave2wave** [comment]
It looks like the page has been fixed and this issue should be closed
