### ISSUE TITLE
Sentence does not make sense: dist.a.o is not the release host

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-website#47]
https://github.com/apache/infrastructure-website/blob/b5e2d7758d038c4649fcef9c904d0f6cb3bbcb01/content/pages/mirrors.md#L8

**Comment by cottage14** [comment]
Sebb, what would you suggest as appropriate text?

**Comment by sebbASF** [comment]
I don't know what the sentence is trying to say.

However I do know that dist.a.o is not the end target for releases, only a stepping stone.

I suspect you will need to ask Infra what the intent is.

**Comment by gmcdonald** [comment]
This is no longer relevant
