### ISSUE TITLE
Expose date on blog posts

### ISSUE THREAD

**Issue by kwin** [apache/infrastructure-website#76]
Although the date is part of the metadata, e.g. in https://github.com/apache/infrastructure-website/blob/master/content/blog/jira-public-signup-disabled.md, it is not exposed on the rendered HTML: https://infra.apache.org/blog/jira-public-signup-disabled

It is exposed though on the index page: https://infra.apache.org/blog/

For blog articles this is crucial information.

**Comment by christ** [comment]
Fixed in commit https://github.com/apache/infrastructure-website/commit/95af91f0e3410af46627a5a77ef3723f86b7cbfe
