### ISSUE TITLE
<var> tags are being escaped so appear literally in the output

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-website#87]
It looks like `<var>` tags don't work inside back-quotes

**Comment by cottage14** [comment]
In the section on 'how do I find out who is subscribed to a mailing list?' the display was poor because of the use of <var> tags, and there was inconsistency in the variables used in the examples. I have cleaned up the display and made the examples more consistent, with an introductory explanation.

**Comment by cottage14** [comment]
completed
